### PR TITLE
feat(client-mods): support more client mods

### LINKED ISSUE #14: feat(client-mods): add support for `vencord` and `replugged`
We already have support for [BetterDiscord](https://betterdiscord.app), so it is most likely in the best interests of the project to add support to both [Replugged](https://replugged.dev) and [Vencord](https://vencord.dev)

### PR DESCRIPTION
**Pull request by AceLikesGhosts**
oh god

### CODE REVIEW

**Comment by AceLikesGhosts** [comment]
TODO: Find a way to grab the Asset Manager on Replugged so it can actually display images. After that, we are done for replugged! (:

**Comment by l1mey112** [comment]
gj ace

**Comment by AceLikesGhosts** [comment]
>  gj ace

thank

i was going to write a [vencord](https://vencord.dev) plugin but their license is GPLv3 for their plugin template and im not going to write my own buildchain just for them. atleast [replugged](https://replugged.dev) is good enough to make their plugin template MIT

EDIT:
"moment of realization"

**Comment by AceLikesGhosts** [comment]
[replugged](https://replugged.dev) (i love u asportnoy) plugin is now finished! :D 
time to go look more at [shitcord (vencord)](https://vencord.dev) and how i can get around their [shitty license](https://www.gnu.org/licenses/gpl-3.0.en.html) without having to change this project from the [so much better, MIT license](https://opensource.org/license/mit/)

**Comment by AceLikesGhosts** [comment]
Going to merge this because I don't plan on writing something for [shitcord](https://vencord.dev) rn

**Pull request merged**
